// Mocks generated by Mockito 5.4.6 from annotations
// in webchat/test/unit/bloc_unit_test/message_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:webchat/src/domain/entity/message_entity.dart' as _i4;
import 'package:webchat/src/domain/repo/message_repo.dart' as _i2;
import 'package:webchat/src/domain/usecase/message_usecase/store_message_usecase.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MessageRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepo extends _i1.Mock implements _i2.MessageRepo {
  MockMessageRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MessageEntity>> getMessagesByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesByUserId, [userId]),
            returnValue: _i3.Future<List<_i4.MessageEntity>>.value(
              <_i4.MessageEntity>[],
            ),
          )
          as _i3.Future<List<_i4.MessageEntity>>);

  @override
  _i3.Stream<List<_i4.MessageEntity>> watchMessagesByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessagesByUserId, [userId]),
            returnValue: _i3.Stream<List<_i4.MessageEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.MessageEntity>>);

  @override
  _i3.Future<void> storeMessage(_i4.MessageEntity? message) =>
      (super.noSuchMethod(
            Invocation.method(#storeMessage, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMessageStatus(
    int? messageId,
    _i4.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageStatus, [messageId, status]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StoreMessageUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreMessageUsecase extends _i1.Mock
    implements _i5.StoreMessageUsecase {
  MockStoreMessageUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i4.MessageEntity? message) =>
      (super.noSuchMethod(
            Invocation.method(#call, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
