// Mocks generated by Mockito 5.4.6 from annotations
// in webchat/test/unit/bloc_unit_test/websocket_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:webchat/api/socket/websocket_service.dart' as _i2;
import 'package:webchat/src/domain/repo/websocket_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i2.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.WebSocketConnectionStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.WebSocketConnectionStatus.disconnected,
          )
          as _i3.WebSocketConnectionStatus);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i3.WebSocketConnectionStatus> get statusStream =>
      (super.noSuchMethod(
            Invocation.getter(#statusStream),
            returnValue: _i4.Stream<_i3.WebSocketConnectionStatus>.empty(),
          )
          as _i4.Stream<_i3.WebSocketConnectionStatus>);

  @override
  _i4.Stream<Map<String, dynamic>> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get typingStream =>
      (super.noSuchMethod(
            Invocation.getter(#typingStream),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<void> connect({String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {#url: url}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void sendMessage(
    String? message, {
    int? userId,
    int? receiverId,
    String? messageId,
  }) => super.noSuchMethod(
    Invocation.method(
      #sendMessage,
      [message],
      {#userId: userId, #receiverId: receiverId, #messageId: messageId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingIndicator(bool? isTyping, {int? userId, int? receiverId}) =>
      super.noSuchMethod(
        Invocation.method(
          #sendTypingIndicator,
          [isTyping],
          {#userId: userId, #receiverId: receiverId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
